public with sharing class ErrorMessageNotesController {
//    private final Notes__c note;
    
//    public String errorMessage {get;set;}
    
//    private ApexPages.StandardController stdController;
    

//    public ErrorMessageNotesController(ApexPages.StandardController stdController) {
//        this.note = (Notes__c)stdController.getRecord();
//        this.stdController = stdController;
//        errorMessage = '';
//    }
        
        
//    public PageReference save() {
//        errorMessage = '';
//        try {
            //Then do the insert
//            upsert note;
            
//            PageReference parentPage = new PageReference('/'+ note.Account__c);
//            parentPage.setRedirect(true);
//           return parentPage;

            
            /*controller.save();*/
        
//            }
        
//         catch (DMLException e) {
//             errorMessage = e.getMessage();
//             ApexPages.addMessages(e);
//             return null;
            

//        }
        
         
//    }
}