public with sharing class TriggerContextConstants {
    // These are used to set the context in trigger handler tests
    public static final String BEFORE_INSERT = 'before insert';
    public static final String BEFORE_UPDATE = 'before update';
    public static final String BEFORE_DELETE = 'before delete';
    public static final String AFTER_INSERT = 'after insert';
    public static final String AFTER_UPDATE = 'after update';
    public static final String AFTER_DELETE = 'after delete';
    public static final String AFTER_UNDELETE = 'after undelete';
}